spring.application.name=Digital_Bank

spring.datasource.url=jdbc:mysql://localhost:3306/digital_bank?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Boaventura

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true   

spring.jackson.serialization.fail-on-self-references=false
spring.jackson.serialization.fail-on-empty-beans=false

spring.jackson.deserialization.fail-on-unknown-properties=false
spring.jackson.default-property-inclusion=non_null
